# Generated by Django 5.1.7 on 2025-06-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_movieview_user_alter_movieview_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieview',
            old_name='ip_address',
            new_name='ip',
        ),
    ]
